### ISSUE TITLE
landscape mode  sort??

### ISSUE THREAD

**Issue by kakashilw** [mikwiseman/RoboReader#1]
When read some cartoon pdf book   in landscape mode， it's order is from right to left,

did it  support change order in landscape mode??

**Comment by vaivaikitay** [comment]
1) You want to reverse PDF (so, page number one would be on the plce of page number last)?
In this case you could revers pdf on your computer, or you can do it online, or on your server.

2) Or you want to start reading pdf from the last page?
In this case you could set it in code - in RoboViewController.m change "showDocument" method to this one:
- (void)showDocument {
  
  [self updateScrollViewContentSize];
  
  startPageNumber = [document.pageCount intValue];
  
  [self showDocumentPage:startPageNumber fastScroll:NO];
  
  document.lastOpen = [NSDate date];

}
