### ISSUE TITLE
Problems on landscape when presented modally

### ISSUE THREAD

**Issue by laplacesdemon** [mikwiseman/RoboReader#5]
When I present it modally like following, it doesn't work properly. After a couple of slides, it stops showing pages. It works when using with a navigation controller. Only happens on modal-landscape. 

```
[self presentViewController:pdfCtrl animated:YES completion:nil];
```

**Comment by vaivaikitay** [comment]
Hello,
RoboReader doesn' t support modal presentation yet.

**Comment by laplacesdemon** [comment]
Why not? What could possibly the problem? —
Suleyman Melikoglu

**Comment by vaivaikitay** [comment]
It's because of some constants of sizes in code.
I think, refactoring of the code (replacing all magic numbers to screen size values - and so on) would fix it.
