### ISSUE TITLE
Crash when load a long pdf file

### ISSUE THREAD

**Issue by nvnguyenit** [mikwiseman/RoboReader#6]
Hi Mikhail Viceman!

Your library really good! I use it, when it load a single pdf file (320*1114  px). App crash, may be you can check at viewDidLoad method in Roboviewcontroller

**Comment by vaivaikitay** [comment]
Hello!
Could you give me crash log, please?

**Comment by vaivaikitay** [comment]
P.S. Sorry for such a big answer delay
